### ISSUE TITLE
快手工作室版报错 请求修复

### ISSUE THREAD

**Issue by 2563411574** [hongke120/qlym#6]
IP已经换了但是还是提示这个

❗️快手极速版, 错误!
TypeError: Cannot read properties of null (reading 'taskRewardName')
    at _0x9d8dda.luckdrawTasksReward (/ql/data/scripts/raw_master_ksjs6w.js:812:120)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x9d8dda.luckdrawTasks (/ql/data/scripts/raw_master_ksjs6w.js:789:63)
    at async _0x9d8dda.luckydraw (/ql/data/scripts/raw_master_ksjs6w.js:712:32)
    at async _0x9d8dda.luckdrawInfo (/ql/data/scripts/raw_master_ksjs6w.js:680:9)
    at async /ql/data/scripts/raw_master_ksjs6w.js:960:9

**Comment by hongke120** [comment]
本地也不能用了
